### ISSUE TITLE
[Error] PlatformException(create_failed, can't create a view on a headless engine, null

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/Flutter-SDK#120]
After I joined RTC channel, my `AgoraRendarView` couldn't create with this error.
After disposing of the view, I generated a new view again and it worked.
Is it a bug ? Is it possible to work around this error?

```dart
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(create_failed, can't create a view on a headless engine, null)
[   +1 ms] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
[   +2 ms] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
[        ] <asynchronous suspension>
[        ] #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:162)
[        ] <asynchronous suspension>
[        ] #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:623)
[        ] <asynchronous suspension>
```

### Version
```
agora_rtc_engine: ^1.0.5
```

### flutter doctor -v

```
[✓] Flutter (Channel master, v1.15.4-pre.97, on Mac OS X 10.14.4 18E227, locale ja-JP)
    • Flutter version 1.15.4-pre.97 at /Users/user/flutter
    • Framework revision f81588a5a3 (8 weeks ago), 2020-02-18 16:33:55 -0800
    • Engine revision 77c5812d48
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 999eeea5a3)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone • c549c0ec2e3417410004904f9f77136fe4c99ffd • ios • iOS 12.1.1

• No issues found!

```

**Comment by yukitaka13-1110** [comment]
Once I get this error, I keep getting this error unless I quit the app.
It is critical for my application.

**Comment by LichKing-2234** [comment]
it seems like a bug of Flutter.
https://github.com/flutter/flutter/issues/36310

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
