### ISSUE TITLE
Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/Flutter-SDK#146]
### Explain
I tried to create remote native view but I got `PlatformException` and black screen.
My native view was displayed and published correctly but remote view weren't.

### Error log
```dart
[  +32 ms] E/flutter (23201): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int
java.lang.Integer.intValue()' on a null object reference, null)
[        ] E/flutter (23201): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
[        ] E/flutter (23201): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
[        ] E/flutter (23201): <asynchronous suspension>
[        ] E/flutter (23201): #2      AgoraRtcEngine.removeNativeView (package:agora_rtc_engine/agora_rtc_engine.dart:704)
[        ] E/flutter (23201): <asynchronous suspension>
[        ] E/flutter (23201): 

```

### Other
Is it a bug ?  What should I do ?
Thank you!

### Information
Android 9.0 API Level 28

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale)
    • Flutter version 1.18.0-6.0.pre at /Users/***/flutter
    • Framework revision 84c84fb249 (8 weeks ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • android-arm64 • Android 9 (API 28)

```

**Comment by yukitaka13-1110** [comment]
### Local view

Displayed correctly and published to remote.

### Remote view

Didn't displayed.

What are there difference between?

**Comment by yukitaka13-1110** [comment]
I confirmed RTC user joined successfully.
```dart
onJoinChannelSuccess -> 566529503
onUserJoined -> 1167749986
```

I tried at Android 7.0 and failed too.

**Comment by yukitaka13-1110** [comment]
I could display remote view but couldn't why this bug occurred.

**Comment by yukitaka13-1110** [comment]
#140 Solved
