### ISSUE TITLE
playEffect method sends "loopback" parameter instead of "loopcount"

### ISSUE THREAD

**Issue by saraeng** [AgoraIO/Flutter-SDK#152]
It causes the following error:
```
PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (31119): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
I/flutter (31119): <asynchronous suspension>
I/flutter (31119): #2      AgoraRtcEngine.playEffect (package:agora_rtc_engine/agora_rtc_engine.dart:1111:20)
```

By the way, Can I use this method to play sound on my app to the local user without joining a call? I mean, if I want the user to listen to a song for example and decide whether or not he wants to join a voice channel in the middle of the song.
Can this method get remote url too?

**Comment by LichKing-2234** [comment]
fixed in dev version

**Comment by fedotxxl** [comment]
I'm using 3.0.1-dev.7 version and receiving the same exception on calling `_engine.leaveChannel()`; and `_engine.destroy();`

```
E/flutter (21552): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(7, not initialized, null)
E/flutter (21552): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (21552): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (21552): <asynchronous suspension>
E/flutter (21552): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (21552): #3      RtcEngine._invokeMethod (package:agora_rtc_engine/src/rtc_engine.dart:54:27)
E/flutter (21552): #4      RtcEngine.leaveChannel (package:agora_rtc_engine/src/rtc_engine.dart:218:12)
E/flutter (21552): #5      _Bloc.dispose (package:onlive_seller_app/videoCall/video_call_page.dart:114:13)
```

Can you help?

**Comment by LichKing-2234** [comment]
@fedotxxl have you call `create` and `joinChannel`?
