### ISSUE TITLE
Android Grey Screen, Please init RtcEngine first!

### ISSUE THREAD

**Issue by jamesmoore255** [AgoraIO/Flutter-SDK#207]
**Describe the bug**

When trying to run an Agora video call in release mode for Android I get a grey screen and a number of errors. including:

```
Please init RtcEngine first!, null, java.lang.RuntimeException: Please init RtcEngine first!

PlatformException(error, Incomplete hierarchy for class RtcEngineManager, unresolved classes [io.agora.rtc.base.IRtcEngine$RtcEngineInterface], null, java.lang.IllegalStateException: Incomplete hierarchy for class RtcEngineManager, unresolved classes [io.agora.rtc.base.IRtcEngine$RtcEngineInterface]
```

**To Reproduce**
1. Build the app for Android in release mode
2. Initiate a video call

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Incomplete hierarchy for class RtcEngineManager, unresolved classes [io.agora.rtc.base.IRtcEngine$RtcEngineInterface], null, java.lang.IllegalStateException: Incomplete hierarchy for class RtcEngineManager, unresolved classes [io.agora.rtc.base.IRtcEngine$RtcEngineInterface]
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeErrorReporter.reportIncompleteHierarchy(Unknown Source:41)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassTypeConstructor.computeSupertypes(Unknown Source:211)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(Unknown Source:4)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor$supertypes$1.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValueWithPostCompute.invoke(Unknown Source:15)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValueWithPostCompute.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.types.AbstractTypeConstructor.getSupertypes(Unknown Source:2)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getNonDeclaredVariableNames(Unknown Source:8)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(Unknown Source:12)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$variableNamesLazy$2.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(Unknown Source:10)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNamesLazy(Unknown Source:7)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getVariableNames(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.addFunctionsAndProperties(Unknown Source:14)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(Unknown Source:36)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(Unknown Source:12)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(Unknown Source:86)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(Unknown Source:12)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(Unknown Source:18)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(Unknown Source:17)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(Unknown Source:10)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(Unknown Source:17)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(Unknown Source:0)
E/flutter ( 7689): 	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(Unknown Source:8)
E/flutter ( 7689): 	at kotlin.reflect.full.KClasses.getDeclaredMemberFunctions(Unknown Source:17)
E/flutter ( 7689): 	at io.agora.agora_rtc_engine.AgoraRtcEnginePlugin.onMethodCall(Unknown Source:20)
E/flutter ( 7689): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter ( 7689): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter ( 7689): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter ( 7689): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7689): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 7689): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 7689): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 7689): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7689): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 7689): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 7689): )
E/flutter ( 7689): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter ( 7689): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #2      RtcEngine.createWithAreaCode (package:agora_rtc_engine/src/rtc_engine.dart:80)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #3      _VideoCallScreenState._initAgoraRtcEngine (package:flutter_loop/src/video_chat/screens/video_call_screen.dart:155)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #4      _VideoCallScreenState.initializeAgora (package:flutter_loop/src/video_chat/screens/video_call_screen.dart:102)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): 
E/flutter ( 7689): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Please init RtcEngine first!, null, java.lang.RuntimeException: Please init RtcEngine first!
E/flutter ( 7689): 	at io.agora.rtc.base.RtcSurfaceView.<init>(Unknown Source:36)
E/flutter ( 7689): 	at io.agora.agora_rtc_engine.AgoraSurfaceView.<init>(Unknown Source:29)
E/flutter ( 7689): 	at io.agora.agora_rtc_engine.AgoraSurfaceViewFactory.create(Unknown Source:32)
E/flutter ( 7689): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(Unknown Source:116)
E/flutter ( 7689): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/flutter ( 7689): 	at android.app.Dialog.show(Dialog.java:313)
E/flutter ( 7689): 	at android.app.Presentation.show(Presentation.java:257)
E/flutter ( 7689): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(Unknown Source:55)
E/flutter ( 7689): 	at io.flutter.plugin.platform.VirtualDisplayController.create(Unknown Source:65)
E/flutter ( 7689): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(Unknown Source:110)
E/flutter ( 7689): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(Unknown Source:152)
E/flutter ( 7689): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(Unknown Source:149)
E/flutter ( 7689): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter ( 7689): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter ( 7689): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter ( 7689): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7689): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 7689): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 7689): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 7689): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7689): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 7689): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 7689): )
E/flutter ( 7689): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter ( 7689): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
E/flutter ( 7689): <asynchronous suspension>
E/flutter ( 7689): 
F/SENTINEL_TAG(10993): SENTINEL_MSG_LIBCUTILS
F/SENTINEL_TAG(10993): SENTINEL_MSG_LIBLOG
F/SENTINEL_TAG(11995): SENTINEL_MSG_LIBCUTILS
F/SENTINEL_TAG(11995): SENTINEL_MSG_LIBLOG
```

**Expected behavior**

The video call should connect and see a video of myself.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a, Samsung Galaxy s9
 - Version 3.1.3

**Comment by LichKing-2234** [comment]
if you want to use render widget, you should init our SDK first

**Comment by jamesmoore255** [comment]
Yeah sorry, It was a mix of not setting minifyEnabled to false and a few of the other issues that you have already addressed.

**Comment by Ash110** [comment]
Hey @jamesmoore255 I've been trying to solve the same issue but haven't found a reliable solution. Could you expand on what worked for you?
