### ISSUE TITLE
 Web: PlatformException(Unimplemented, null, agora_rtc_engine for web doesn't implement 'create', null) on Chrome

### ISSUE THREAD

**Issue by subirats345** [AgoraIO/Flutter-SDK#221]
**Description**
When I tried the last version, 3.1.4, I have an error when I run the examples on Chrome, on both Windows and MacOS. In the [pub dev packcage](https://pub.dev/packages/agora_rtc_engine) I've seen that the web support is enabled. The error is:

```
Error: PlatformException(Unimplemented, null, agora_rtc_engine for web doesn't implement 'create', null)
    at Object.throw_ [as throw] (http://localhost:50627/dart_sdk.js:4351:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:50627/packages/flutter/src/services/system_channels.dart.lib.js:783:19)
    at MethodChannel._invokeMethod (http://localhost:50627/packages/flutter/src/services/system_channels.dart.lib.js:945:47)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50627/dart_sdk.js:37968:33
    at _RootZone.runUnary (http://localhost:50627/dart_sdk.js:37822:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50627/dart_sdk.js:32783:29)
    at handleValueCallback (http://localhost:50627/dart_sdk.js:33331:49)
    at Function._propagateToListeners (http://localhost:50627/dart_sdk.js:33369:17)
    at _Future.new.[_completeWithValue] (http://localhost:50627/dart_sdk.js:33211:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50627/dart_sdk.js:33234:35)
    at Object._microtaskLoop (http://localhost:50627/dart_sdk.js:38083:13)
    at _startMicrotaskLoop (http://localhost:50627/dart_sdk.js:38089:13)
    at http://localhost:50627/dart_sdk.js:33586:9
```

**To Reproduce**
1. `clone `the repo
2. `cd `on the examples folder
3. `pub get`
4. Select **Chrome** as a device, run the app, **JoinChannelVideo** and click on **Join channel**

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/Flutter-SDK/issues/63#issuecomment-737616860
