### ISSUE TITLE
AgoraEventListener 'onVideoSizeChanged' doesn't work 「type '_Smi' is not a subtype of type 'double'」

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/Flutter-SDK#85]
I configured `AgoraRtcEngine.onVideoSizeChanged` event handler.

```dart
AgoraRtcEngine.onVideoSizeChanged = (uid, width, height, elapsed) {
  setState(() {
    _remoteStreamSize = Size(width, height);
  });
};
```

When event fired the following error occurred.

```dart
[+23545 ms] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_Smi' is not a subtype of type 'double'
[        ] #0      AgoraRtcEngine._eventListener (package:agora_rtc_engine/agora_rtc_engine.dart:1396)
[        ] #1      _rootRunUnary (dart:async/zone.dart:1134)
[        ] #2      _CustomZone.runUnary (dart:async/zone.dart:1031)
[        ] #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
[        ] #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
[        ] #5      _DelayedData.perform (dart:async/stream_impl.dart:594)
[        ] #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710)
[        ] #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670)
[        ] #8      _rootRun (dart:async/zone.dart:1122)
[        ] #9      _CustomZone.run (dart:async/zone.dart:1023)
[        ] #10     _CustomZone.runGuarded (dart:async/zone.dart:925)
[        ] #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
[        ] #12     _rootRun (dart:async/zone.dart:1126)
[        ] #13     _CustomZone.run (dart:async/zone.dart:1023)
[        ] #14     _CustomZone.runGuarded (dart:async/zone.dart:925)
[        ] #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
[        ] #16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
[        ] #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)

```

This is my `flutter doctor -v`

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.15.4-pre.97, on Mac OS X 10.14.4 18E227, locale)
    • Flutter version 1.15.4-pre.97 at /Users/*****/flutter
    • Framework revision f81588a5a3 (2 weeks ago), 2020-02-18 16:33:55 -0800
    • Engine revision 77c5812d48
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 999eeea5a3)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

```

**Comment by plutoless** [comment]
you should try avoid doing that. you don't need to change video canvas size based on that callback, just set the render mode to fit of fill, we will fit the video automatically for you into your container.

**Comment by yukitaka13-1110** [comment]
@plutoless 
Thank you for the reply.
I see. But I think this event listener contains a bug.
Isn’t it necessary to fix? Would you please check my error messages.

**Comment by LichKing-2234** [comment]
I will check it and reply to you today

**Comment by LichKing-2234** [comment]
I have published a new version of SDK to `pub.dev`, you can try it later

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
I tried and confirmed.
Thank you so much 👍
